In [1]:
import pandas as pd 
import numpy as np 

data=pd.read_csv("/home/loubna/Code_Projet_Mathia/Mathia/data/Rawson/Rawson_et_al_2018_dat_vF.csv")

In [2]:
print(data.head(1))

   Unnamed: 0                  user_id  Assigned_Criterion  \
0           1  venustraphobic_ibisbill                   3

   Learning_Condition Learning_Condition_Label Learning_Condition_Short_Label  \
0                   3      1 block of 48 items                         Lag 47

   Session_Number Trial_Type  Stim_ID skill_name  ... Correct  \
0               1       test       45      sesuo  ...   False

   Correct_Numeric  correct      Ending_Message Trial_N  \
0                0        0  TIME LIMIT REACHED      49

  Within_Session_Num_Oppts  K_Fold  Opportunities (Default)  \
0                        1       1                        1

   num_opportunities order_id
0                  1        1

[1 rows x 26 columns]

In [3]:
data.columns

Index(['Unnamed: 0', 'user_id', 'Assigned_Criterion', 'Learning_Condition',
       'Learning_Condition_Label', 'Learning_Condition_Short_Label',
       'Session_Number', 'Trial_Type', 'Stim_ID', 'skill_name', 'Target',
       'Retest_Trial', 'List_Number', 'Response', 'RT', 'Answered', 'Correct',
       'Correct_Numeric', 'correct', 'Ending_Message', 'Trial_N',
       'Within_Session_Num_Oppts', 'K_Fold', 'Opportunities (Default)',
       'num_opportunities', 'order_id'],
      dtype='object')

In [5]:
data.head()

,Unnamed: 0,user_id,Assigned_Criterion,Learning_Condition,Learning_Condition_Label,Learning_Condition_Short_Label,Session_Number,Trial_Type,Stim_ID,skill_name,...,Correct,Correct_Numeric,correct,Ending_Message,Trial_N,Within_Session_Num_Oppts,K_Fold,Opportunities (Default),num_opportunities,order_id
0,1,venustraphobic_ibisbill,3,3,1 block of 48 items,Lag 47,1,test,45,sesuo,...,False,0,0,TIME LIMIT REACHED,49,1,1,1,1,1
1,2,venustraphobic_ibisbill,3,3,1 block of 48 items,Lag 47,1,test,32,daina,...,False,0,0,TIME LIMIT REACHED,50,1,1,1,1,2
2,3,venustraphobic_ibisbill,1,3,1 block of 48 items,Lag 47,1,test,10,purvas,...,False,0,0,TIME LIMIT REACHED,51,1,1,1,1,3
3,4,venustraphobic_ibisbill,3,3,1 block of 48 items,Lag 47,1,test,47,pupa,...,True,1,1,TIME LIMIT REACHED,52,1,1,1,1,4
4,5,venustraphobic_ibisbill,3,3,1 block of 48 items,Lag 47,1,test,29,langas,...,False,0,0,TIME LIMIT REACHED,53,1,1,1,1,5

In [50]:
data2=data[["user_id","Stim_ID","skill_name","correct","Session_Number","Learning_Condition_Short_Label",'Trial_N',"order_id","RT","Assigned_Criterion"]]

In [51]:
len(data2)

49491

In [52]:
sess1=data2[data2["Session_Number"]==1]

In [53]:
sess1

,user_id,Stim_ID,skill_name,correct,Session_Number,Learning_Condition_Short_Label,Trial_N,order_id,RT,Assigned_Criterion
0,venustraphobic_ibisbill,45,sesuo,0,1,Lag 47,49,1,8.1,3
1,venustraphobic_ibisbill,32,daina,0,1,Lag 47,50,2,8.1,3
2,venustraphobic_ibisbill,10,purvas,0,1,Lag 47,51,3,8.1,1
3,venustraphobic_ibisbill,47,pupa,1,1,Lag 47,52,4,6.9,3
4,venustraphobic_ibisbill,29,langas,0,1,Lag 47,53,5,8.1,3
...,...,...,...,...,...,...,...,...,...,...
48886,customary_perch,16,gele,1,1,Lag 47,142,94,3.616667,3
48887,customary_perch,38,smegenys,1,1,Lag 47,143,95,4.516667,3
48888,customary_perch,41,batas,1,1,Lag 47,144,96,4.4,3
48889,customary_perch,39,vilkas,1,1,Lag 47,145,97,5.466667,3
48890,customary_perch,13,zirkles,1,1,Lag 47,146,98,6.783333,3

In [54]:
sess1[sess1["Learning_Condition_Short_Label"]=="Lag 7"]["order_id"].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190])

In [55]:
sess1[sess1["Learning_Condition_Short_Label"]=="Lag 15"]["order_id"].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304])

In [11]:
sess1[sess1["Learning_Condition_Short_Label"]=="Lag 15"]["order_id"].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304])

In [56]:
sess1 = sess1.sort_values(
    ["user_id", "order_id"]
).copy()

In [57]:
sess1.dtypes

user_id                           object
Stim_ID                            int64
skill_name                        object
correct                            int64
Session_Number                     int64
Learning_Condition_Short_Label    object
Trial_N                            int64
order_id                           int64
RT                                object
Assigned_Criterion                 int64
dtype: object

In [ ]:
sess1["RT"] = pd.to_numeric(
    sess1["RT"],
    errors="coerce"
)

In [59]:
sess1["time_seconds"] = (
    sess1.groupby("user_id")["RT"]
         .transform(lambda x: x.cumsum().shift(fill_value=0))
)

In [60]:
sess1

,user_id,Stim_ID,skill_name,correct,Session_Number,Learning_Condition_Short_Label,Trial_N,order_id,RT,Assigned_Criterion,time_seconds
36634,algebraic_yorkshireterrier,17,stogas,1,1,Lag 7,9,1,4.516667,1,0.000000
36635,algebraic_yorkshireterrier,6,karalius,0,1,Lag 7,10,2,8.100000,3,4.516667
36636,algebraic_yorkshireterrier,7,pastatas,1,1,Lag 7,11,3,6.583333,3,12.616667
36637,algebraic_yorkshireterrier,5,traukinys,1,1,Lag 7,12,4,5.766667,3,19.200000
36638,algebraic_yorkshireterrier,20,kelnes,0,1,Lag 7,13,5,2.800000,1,24.966667
...,...,...,...,...,...,...,...,...,...,...,...
46744,wooden_vaquita,5,traukinys,1,1,Lag 7,153,105,3.716667,3,514.683331
46745,wooden_vaquita,8,dumai,1,1,Lag 7,154,106,4.883333,3,518.399998
46746,wooden_vaquita,7,pastatas,1,1,Lag 7,155,107,4.483333,3,523.283331
46747,wooden_vaquita,6,karalius,1,1,Lag 7,156,108,3.366667,3,527.766664
46748,wooden_vaquita,8,dumai,1,1,Lag 7,157,109,4.750000,3,531.133331

In [62]:
origin = pd.Timestamp("2019-01-01 09:00:00")

sess1["timestamp"] = (
    origin +
    pd.to_timedelta(sess1["time_seconds"], unit="s")
)

In [63]:
sess1

,user_id,Stim_ID,skill_name,correct,Session_Number,Learning_Condition_Short_Label,Trial_N,order_id,RT,Assigned_Criterion,time_seconds,timestamp
36634,algebraic_yorkshireterrier,17,stogas,1,1,Lag 7,9,1,4.516667,1,0.000000,2019-01-01 09:00:00.000000
36635,algebraic_yorkshireterrier,6,karalius,0,1,Lag 7,10,2,8.100000,3,4.516667,2019-01-01 09:00:04.516667
36636,algebraic_yorkshireterrier,7,pastatas,1,1,Lag 7,11,3,6.583333,3,12.616667,2019-01-01 09:00:12.616667
36637,algebraic_yorkshireterrier,5,traukinys,1,1,Lag 7,12,4,5.766667,3,19.200000,2019-01-01 09:00:19.200000
36638,algebraic_yorkshireterrier,20,kelnes,0,1,Lag 7,13,5,2.800000,1,24.966667,2019-01-01 09:00:24.966667
...,...,...,...,...,...,...,...,...,...,...,...,...
46744,wooden_vaquita,5,traukinys,1,1,Lag 7,153,105,3.716667,3,514.683331,2019-01-01 09:08:34.683331
46745,wooden_vaquita,8,dumai,1,1,Lag 7,154,106,4.883333,3,518.399998,2019-01-01 09:08:38.399998
46746,wooden_vaquita,7,pastatas,1,1,Lag 7,155,107,4.483333,3,523.283331,2019-01-01 09:08:43.283331
46747,wooden_vaquita,6,karalius,1,1,Lag 7,156,108,3.366667,3,527.766664,2019-01-01 09:08:47.766664
46748,wooden_vaquita,8,dumai,1,1,Lag 7,157,109,4.750000,3,531.133331,2019-01-01 09:08:51.133331

In [64]:
sess1=sess1.rename(columns={"Stim_ID":"item_id","skill_name":"KC"}
             )

In [65]:
sess1

,user_id,item_id,KC,correct,Session_Number,Learning_Condition_Short_Label,Trial_N,order_id,RT,Assigned_Criterion,time_seconds,timestamp
36634,algebraic_yorkshireterrier,17,stogas,1,1,Lag 7,9,1,4.516667,1,0.000000,2019-01-01 09:00:00.000000
36635,algebraic_yorkshireterrier,6,karalius,0,1,Lag 7,10,2,8.100000,3,4.516667,2019-01-01 09:00:04.516667
36636,algebraic_yorkshireterrier,7,pastatas,1,1,Lag 7,11,3,6.583333,3,12.616667,2019-01-01 09:00:12.616667
36637,algebraic_yorkshireterrier,5,traukinys,1,1,Lag 7,12,4,5.766667,3,19.200000,2019-01-01 09:00:19.200000
36638,algebraic_yorkshireterrier,20,kelnes,0,1,Lag 7,13,5,2.800000,1,24.966667,2019-01-01 09:00:24.966667
...,...,...,...,...,...,...,...,...,...,...,...,...
46744,wooden_vaquita,5,traukinys,1,1,Lag 7,153,105,3.716667,3,514.683331,2019-01-01 09:08:34.683331
46745,wooden_vaquita,8,dumai,1,1,Lag 7,154,106,4.883333,3,518.399998,2019-01-01 09:08:38.399998
46746,wooden_vaquita,7,pastatas,1,1,Lag 7,155,107,4.483333,3,523.283331,2019-01-01 09:08:43.283331
46747,wooden_vaquita,6,karalius,1,1,Lag 7,156,108,3.366667,3,527.766664,2019-01-01 09:08:47.766664
46748,wooden_vaquita,8,dumai,1,1,Lag 7,157,109,4.750000,3,531.133331,2019-01-01 09:08:51.133331

In [66]:
sess1["user_id"].nunique()

88

In [67]:
sess1.to_csv(
    "/home/loubna/Code_Projet_Mathia/Mathia/data/Rawson/sess1.csv",
    index=False
)

In [32]:
sess2=data[data["Session_Number"]==2]

In [33]:
sess2

,Unnamed: 0,user_id,Assigned_Criterion,Learning_Condition,Learning_Condition_Label,Learning_Condition_Short_Label,Session_Number,Trial_Type,Stim_ID,skill_name,...,Correct,Correct_Numeric,correct,Ending_Message,Trial_N,Within_Session_Num_Oppts,K_Fold,Opportunities (Default),num_opportunities,order_id
298,299,venustraphobic_ibisbill,1,3,1 block of 48 items,Lag 47,2,test,15,vinis,...,False,0,0,TIME LIMIT NOT REACHED,1,1,1,7,7,299
299,300,venustraphobic_ibisbill,1,3,1 block of 48 items,Lag 47,2,test,24,knyga,...,False,0,0,TIME LIMIT NOT REACHED,2,1,1,12,12,300
300,301,venustraphobic_ibisbill,1,3,1 block of 48 items,Lag 47,2,test,5,traukinys,...,False,0,0,TIME LIMIT NOT REACHED,3,1,1,9,9,301
301,302,venustraphobic_ibisbill,1,3,1 block of 48 items,Lag 47,2,test,36,mesa,...,True,1,1,TIME LIMIT NOT REACHED,4,1,1,7,7,302
302,303,venustraphobic_ibisbill,1,3,1 block of 48 items,Lag 47,2,test,26,vanduo,...,False,0,0,TIME LIMIT NOT REACHED,5,1,1,12,12,303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49034,49035,customary_perch,1,3,1 block of 48 items,Lag 47,2,test,12,pliazas,...,False,0,0,TIME LIMIT NOT REACHED,144,5,2,6,6,242
49035,49036,customary_perch,1,3,1 block of 48 items,Lag 47,2,test,23,obuolys,...,True,1,1,TIME LIMIT NOT REACHED,145,5,2,6,6,243
49036,49037,customary_perch,1,3,1 block of 48 items,Lag 47,2,test,34,urvas,...,True,1,1,TIME LIMIT NOT REACHED,146,6,2,7,7,244
49037,49038,customary_perch,1,3,1 block of 48 items,Lag 47,2,test,18,ugnis,...,True,1,1,TIME LIMIT NOT REACHED,147,6,2,7,7,245
49038,49039,customary_perch,1,3,1 block of 48 items,Lag 47,2,test,12,pliazas,...,True,1,1,TIME LIMIT NOT REACHED,148,6,2,7,7,246

In [ ]:
# dernier essai de S1 pour chaque utilisateur
last_s1 = (
    sess1.sort_values(["user_id", "order_id"])
         .groupby("user_id")
         .tail(1)
         [["user_id", "timestamp", "RT"]]
         .copy()
)
last_s1["end_s1"] = (
    last_s1["timestamp"]
    + pd.to_timedelta(last_s1["RT"], unit="s")
)

# début de S2
last_s1["start_s2"] = (
    last_s1["end_s1"] + pd.Timedelta(days=7)
)

In [35]:
sess2 = sess2.merge(
    last_s1[["user_id", "start_s2"]],
    on="user_id",
    how="left"
)

In [36]:
# 1. Trier S2 dans l'ordre des essais
sess2 = sess2.sort_values(
    ["user_id", "order_id"]
).copy()

# 2. RT numérique
sess2["RT"] = pd.to_numeric(
    sess2["RT"],
    errors="coerce"
)

# 3. Remplacer les RT manquants
sess2["RT"] = sess2["RT"].fillna(sess2["RT"].median())

# 4. Temps relatif au début de S2
sess2["time_seconds"] = (
    sess2.groupby("user_id")["RT"]
         .transform(
             lambda x: x.cumsum().shift(fill_value=0)
         )
)

# 5. Timestamp réel/reconstruit de chaque essai S2
sess2["timestamp"] = (
    sess2["start_s2"]
    + pd.to_timedelta(sess2["time_seconds"], unit="s")
)

In [37]:
sess2.columns

Index(['Unnamed: 0', 'user_id', 'Assigned_Criterion', 'Learning_Condition',
       'Learning_Condition_Label', 'Learning_Condition_Short_Label',
       'Session_Number', 'Trial_Type', 'Stim_ID', 'skill_name', 'Target',
       'Retest_Trial', 'List_Number', 'Response', 'RT', 'Answered', 'Correct',
       'Correct_Numeric', 'correct', 'Ending_Message', 'Trial_N',
       'Within_Session_Num_Oppts', 'K_Fold', 'Opportunities (Default)',
       'num_opportunities', 'order_id', 'start_s2', 'time_seconds',
       'timestamp'],
      dtype='object')

In [38]:
sess2=sess2[["user_id","Stim_ID","skill_name","correct","Session_Number","Learning_Condition_Short_Label",'Trial_N',"order_id","RT","timestamp","Assigned_Criterion"]]

In [39]:
sess2=sess2.rename(columns={"Stim_ID":"item_id","skill_name":"KC"})

In [43]:
sess2["Assigned_Criterion"].unique()

array([1])

In [163]:
sess2.to_csv(
    "/home/loubna/Code_Projet_Mathia/Mathia/data/Rawson/sess2.csv",
    index=False
)

In [49]:
sess1=data[data["Session_Number"]==6]
sess1["Assigned_Criterion"].unique()

array([1])